### ISSUE TITLE
Java Build fails

### ISSUE THREAD

**Issue by FalkWolsky** [openblocks-dev/openblocks#170]
I use VS Code. In launch.json i added the VM Options:

`{
	"type": "java",
	"name": "Launch ServerApplication(1)",
	"request": "launch",
	"mainClass": "com.openblocks.api.ServerApplication",
	"projectName": "openblocks-server",
	"vmArgs": "-Dpf4j.mode=development -Dpf4j.pluginsDir=openblocks-plugins -Dspring.profiles.active=openblocks -XX:+AllowRedefinitionToAddDeleteMethods"
}`

Then i try to start  com.openblocks.api.ServerApplication as advised here: https://github.com/openblocks-dev/openblocks/tree/develop/server

However, already at this stage i get the warning "build failed". By ignoring this i run in the following error log (Debug and Run Mode)

OpenJDK 64-Bit Server VM warning: Option AllowRedefinitionToAddDeleteMethods was deprecated in version 13.0 and will likely be removed in a future release.
19:38:58.551 [main] DEBUG reactor.util.Loggers - Using Slf4j logging framework
2023-01-07 19:39:00.446 INFO org.hibernate.validator.internal.util.Version#<clinit>:21    [background-preinit]: HV000001: Hibernate Validator 6.2.5.Final 
2023-01-07 19:39:00.524 INFO org.springframework.boot.StartupInfoLogger#logStarting:55    [main]: Starting ServerApplication using Java 17.0.2 on Falks-MacBook-Pro-2.local with PID 21911 (/Users/falkwolsky/Development/Human_Factor/openblocks/openblocks/server/openblocks-server/target/classes started by falkwolsky in /Users/falkwolsky/Development/Human_Factor/openblocks/openblocks) 
2023-01-07 19:39:00.525 INFO org.springframework.boot.SpringApplication#logStartupProfileInfo:651    [main]: The following 1 profile is active: "openblocks" 
2023-01-07 19:39:03.359 INFO o.s.d.r.config.RepositoryConfigurationDelegate#multipleStoresDetected:262    [main]: Multiple Spring Data modules found, entering strict repository configuration mode 
2023-01-07 19:39:03.367 INFO o.s.d.r.config.RepositoryConfigurationDelegate#registerRepositoriesIn:132    [main]: Bootstrapping Spring Data Reactive MongoDB repositories in DEFAULT mode. 
2023-01-07 19:39:03.907 INFO o.s.d.r.config.RepositoryConfigurationDelegate#registerRepositoriesIn:201    [main]: Finished Spring Data repository scanning in 515 ms. Found 19 Reactive MongoDB repository interfaces. 
2023-01-07 19:39:04.784 INFO o.s.d.r.config.RepositoryConfigurationDelegate#multipleStoresDetected:262    [main]: Multiple Spring Data modules found, entering strict repository configuration mode 
2023-01-07 19:39:04.786 INFO o.s.d.r.config.RepositoryConfigurationDelegate#registerRepositoriesIn:132    [main]: Bootstrapping Spring Data Redis repositories in DEFAULT mode. 
2023-01-07 19:39:04.826 INFO o.s.d.r.config.RepositoryConfigurationDelegate#registerRepositoriesIn:201    [main]: Finished Spring Data repository scanning in 28 ms. Found 0 Redis repository interfaces. 
2023-01-07 19:39:05.522 INFO o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker#postProcessAfterInitialization:376    [main]: Bean 'org.springframework.security.config.annotation.method.configuration.ReactiveMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.ReactiveMethodSecurityConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
2023-01-07 19:39:05.630 WARN o.s.context.support.AbstractApplicationContext#refresh:591    [main]: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean. 
2023-01-07 19:39:05.657 INFO o.s.b.a.l.ConditionEvaluationReportLoggingListener#logMessage:136    [main]: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
2023-01-07 19:39:05.684 ERROR org.springframework.boot.SpringApplication#reportFailure:835    [main]: Application run failed 
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:163)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
        at com.openblocks.api.ServerApplication.main(ServerApplication.java:51)
Caused by: org.springframework.context.ApplicationContextException: Unable to start ServletWebServerApplicationContext due to missing ServletWebServerFactory bean.
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getWebServerFactory(ServletWebServerApplicationContext.java:210)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
        ... 7 common frames omitted

**Comment by jerry-goodman** [comment]
Sorry, I can't reproduce this issue, please make sure the code is up to date. And it is recommended to start openblocks server with IntelliJ IDEA.

**Comment by FalkWolsky** [comment]
The error happens when the connection to MongoDB could not be made.
Maybe to add bit more error handling for this case.
