### ISSUE TITLE
application failed to start

### ISSUE THREAD

**Issue by rj-wangshunan** [openblocks-dev/openblocks#233]
Hello.
I use local mongoDB and redis when use idea start application the error logs is fellow:

```
The dependencies of some of the beans in the application context form a cycle:

   applicationApiService (field private com.openblocks.api.home.SessionUserService com.openblocks.api.application.ApplicationApiService.sessionUserService)
      ↓
   sessionUserServiceImpl (field private com.openblocks.domain.organization.service.OrgMemberService com.openblocks.api.home.SessionUserServiceImpl.orgMemberService)
┌─────┐
|  orgMemberServiceImpl (field private com.openblocks.domain.organization.service.OrganizationService com.openblocks.domain.organization.service.OrgMemberServiceImpl.organizationService)
↑     ↓
|  organizationServiceImpl (field private com.openblocks.domain.organization.service.OrgMemberService com.openblocks.domain.organization.service.OrganizationServiceImpl.orgMemberService)
└─────┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
 
2023-02-02 15:21:34.117 ERROR c.o.i.l.ReloadableCache$ReloadableCacheBuilder#lambda$startScheduledReloadTask$0:90    [pool-3-thread-1]: scheduled load error 
java.lang.IllegalStateException: state should be: server session pool is open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:79)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCallable] :
	reactor.core.publisher.Mono.fromCallable
	com.mongodb.reactivestreams.client.internal.ClientSessionHelper.createClientSessionMono(ClientSessionHelper.java:60)
Error has been observed at the following site(s):
	*___Mono.fromCallable ⇢ at com.mongodb.reactivestreams.client.internal.ClientSessionHelper.createClientSessionMono(ClientSessionHelper.java:60)
	|_           Mono.map ⇢ at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$6(OperationExecutorImpl.java:79)
	|_ Mono.switchIfEmpty ⇢ at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$6(OperationExecutorImpl.java:81)
	|_       Mono.flatMap ⇢ at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$6(OperationExecutorImpl.java:83)
	*___________Mono.from ⇢ at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.execute(OperationExecutorImpl.java:77)
	|_                    ⇢ at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.createReadOperationMono(MongoOperationPublisher.java:459)
	|_                    ⇢ at com.mongodb.reactivestreams.client.internal.MongoOperationPublisher.createReadOperationMono(MongoOperationPublisher.java:451)
	|_           Mono.map ⇢ at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.batchCursor(BatchCursorPublisher.java:129)
	|_                    ⇢ at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.batchCursor(BatchCursorPublisher.java:125)
	*_________Flux.create ⇢ at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.subscribe(BatchCursorFlux.java:42)
	*___________Flux.from ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.lambda$executeFindMultiInternal$90(ReactiveMongoTemplate.java:2878)
	|_     Flux.concatMap ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.lambda$executeFindMultiInternal$90(ReactiveMongoTemplate.java:2879)
	*____Mono.flatMapMany ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.createFlux(ReactiveMongoTemplate.java:651)
	|_    Flux.onErrorMap ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.createFlux(ReactiveMongoTemplate.java:651)
	|_                    ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.executeFindMultiInternal(ReactiveMongoTemplate.java:2877)
	|_                    ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.doFind(ReactiveMongoTemplate.java:2505)
	|_                    ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.doFind(ReactiveMongoTemplate.java:2487)
	|_                    ⇢ at org.springframework.data.mongodb.core.ReactiveMongoTemplate.find(ReactiveMongoTemplate.java:886)
	|_                    ⇢ at org.springframework.data.mongodb.repository.support.SimpleReactiveMongoRepository.findAll(SimpleReactiveMongoRepository.java:507)
	|_                    ⇢ at org.springframework.data.mongodb.repository.support.SimpleReactiveMongoRepository.findAll(SimpleReactiveMongoRepository.java:184)
	*______Flux.usingWhen ⇢ at org.springframework.data.repository.core.support.RepositoryMethodInvoker$ReactiveInvocationListenerDecorator.decorate(RepositoryMethodInvoker.java:242)
	|_        Flux.filter ⇢ at com.openblocks.infra.config.AutoReloadConfigFactory.lambda$init$2(AutoReloadConfigFactory.java:35)
	|_   Flux.collectList ⇢ at com.openblocks.infra.config.AutoReloadConfigFactory.lambda$init$2(AutoReloadConfigFactory.java:36)
	|_           Mono.map ⇢ at com.openblocks.infra.config.AutoReloadConfigFactory.lambda$init$2(AutoReloadConfigFactory.java:37)
Original Stack Trace:
		at com.mongodb.assertions.Assertions.isTrue(Assertions.java:79)
		at com.mongodb.internal.session.ServerSessionPool.get(ServerSessionPool.java:85)
		at com.mongodb.internal.session.BaseClientSessionImpl.<init>(BaseClientSessionImpl.java:49)
		at com.mongodb.reactivestreams.client.internal.ClientSessionPublisherImpl.<init>(ClientSessionPublisherImpl.java:57)
		at com.mongodb.reactivestreams.client.internal.ClientSessionHelper.createClientSession(ClientSessionHelper.java:90)
		at com.mongodb.reactivestreams.client.internal.ClientSessionHelper.lambda$createClientSessionMono$1(ClientSessionHelper.java:60)
		at reactor.core.publisher.MonoCallable.subscribe(MonoCallable.java:57)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
		at com.mongodb.reactivestreams.client.internal.OperationExecutorImpl.lambda$execute$6(OperationExecutorImpl.java:99)
		at reactor.core.publisher.MonoFromPublisher.subscribe(MonoFromPublisher.java:63)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
		at reactor.core.publisher.Mono.subscribeWith(Mono.java:4512)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4368)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4304)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4276)
		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$1(BatchCursorFlux.java:48)
		at reactor.core.publisher.FluxCreate$BaseSink.onRequest(FluxCreate.java:557)
		at reactor.core.publisher.FluxCreate$SerializedFluxSink.onRequest(FluxCreate.java:271)
		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.lambda$subscribe$2(BatchCursorFlux.java:44)
		at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:95)
		at reactor.core.publisher.Flux.subscribe(Flux.java:8466)
		at com.mongodb.reactivestreams.client.internal.BatchCursorFlux.subscribe(BatchCursorFlux.java:68)
		at com.mongodb.reactivestreams.client.internal.BatchCursorPublisher.subscribe(BatchCursorPublisher.java:121)
		at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:67)
		at reactor.core.publisher.Flux.subscribe(Flux.java:8466)
		at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
		at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:62)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172)
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onError(FluxFilterFuseable.java:162)
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onError(FluxMapFuseable.java:340)
		at reactor.core.publisher.Operators.error(Operators.java:198)
		at reactor.core.publisher.MonoError.subscribe(MonoError.java:53)
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
		at reactor.core.publisher.Flux.subscribe(Flux.java:8466)
		at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:94)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4397)
		at reactor.core.publisher.Mono.block(Mono.java:1706)
		at com.openblocks.infra.localcache.ReloadableCache$ReloadableCacheBuilder.lambda$startScheduledReloadTask$0(ReloadableCache.java:87)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99)
		at reactor.core.publisher.Mono.block(Mono.java:1707)
		at com.openblocks.infra.localcache.ReloadableCache$ReloadableCacheBuilder.lambda$startScheduledReloadTask$0(ReloadableCache.java:87)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
		at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
		at java.base/java.lang.Thread.run(Thread.java:833)
2023-02-02 15:21:37.110 ERROR c.o.i.l.ReloadableCache$ReloadableCacheBuilder#lambda$startScheduledReloadTask$0:90    [pool-3-thread-1]: scheduled load error 
java.lang.IllegalStateException: state should be: server session pool is open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:79)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCallable] :
	reactor.core.publisher.Mono.fromCallable
	com.mongodb.reactivestreams.client.internal.ClientSessionHelper.createClientSessionMono(ClientSessionHelper.java:60)
```

**Comment by neon-balcony** [comment]
Hey @Tyrentselector it seems v1.1.1 is an old version, please kindly update Openblocks to the latest version: https://docs.openblocks.dev/self-hosting#update

**Comment by rj-wangshunan** [comment]
Tank you @neon-balcony ! But i wanna start Openblocks server locally not use docker. Do you have a document to show how start openblocks server locally? I fellowed the document `server/README.md` but application failed to start.

**Comment by neon-balcony** [comment]
Are you using an IDE? I notice that you are confronting with `circular references` issue and since we've resolved this in [application-openblocks.yml](https://github.com/openblocks-dev/openblocks/blob/develop/server/api-service/openblocks-server/src/main/resources/application-openblocks.yml) it seems that you're not using the correct spring profile. Please carefully check these startup settings here:
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/118174126/216510410-59658fc7-515a-46ef-9754-8634d23a4a3b.png">

**Comment by rj-wangshunan** [comment]
> Are you using an IDE? I notice that you are confronting with `circular references` issue and since we've resolved this in [application-openblocks.yml](https://github.com/openblocks-dev/openblocks/blob/develop/server/api-service/openblocks-server/src/main/resources/application-openblocks.yml) it seems that you're not using the correct spring profile. Please carefully check these startup settings here: <img alt="image" width="1068" src="https://user-images.githubusercontent.com/118174126/216510410-59658fc7-515a-46ef-9754-8634d23a4a3b.png">

Thanks!
